"""add timestamps to product_types

Revision ID: 7d5f683e1141
Revises: 82a360bafcad
Create Date: 2026-05-31 18:28:27.996163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5f683e1141'
down_revision: Union[str, Sequence[str], None] = '82a360bafcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('product_types', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_types', 'updated_at')
    op.drop_column('product_types', 'created_at')
    # ### end Alembic commands ###
