"""fix auction model

Revision ID: 82a360bafcad
Revises: a3842e5c8596
Create Date: 2026-05-31 17:56:54.223850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82a360bafcad'
down_revision: Union[str, Sequence[str], None] = 'a3842e5c8596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('buyout_price', sa.Float(), nullable=True))
    op.add_column('auctions', sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'SOLD', 'CANCELLED', name='auctionstatus'), nullable=False))
    op.add_column('auctions', sa.Column('product_type_id', sa.Integer(), nullable=False))
    op.add_column('auctions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('auctions_producty_type_id_fkey'), 'auctions', type_='foreignkey')
    op.create_foreign_key(None, 'auctions', 'product_types', ['product_type_id'], ['id'])
    op.drop_column('auctions', 'update_at')
    op.drop_column('auctions', 'producty_type_id')
    op.drop_column('auctions', 'buyer_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('buyer_price', postgresql.ENUM('ACTIVE', 'CLOSED', 'SOLD', 'CANCELLED', name='auctionstatus'), autoincrement=False, nullable=False))
    op.add_column('auctions', sa.Column('producty_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('auctions', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'auctions', type_='foreignkey')
    op.create_foreign_key(op.f('auctions_producty_type_id_fkey'), 'auctions', 'product_types', ['producty_type_id'], ['id'])
    op.drop_column('auctions', 'updated_at')
    op.drop_column('auctions', 'product_type_id')
    op.drop_column('auctions', 'status')
    op.drop_column('auctions', 'buyout_price')
    # ### end Alembic commands ###
